apiVersion: v1
kind: Secret
metadata:
  name: nexterp-secret
  namespace: nexterp
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  SPRING_DATASOURCE_USERNAME: bmV4dGVycA==
  SPRING_DATASOURCE_PASSWORD: bmV4dGVycA==
  SPRING_REDIS_PASSWORD: bmV4dGVycA==
  SPRING_RABBITMQ_USERNAME: bmV4dGVycA==
  SPRING_RABBITMQ_PASSWORD: bmV4dGVycA==
