apiVersion: v1
kind: ConfigMap
metadata:
  name: nexterp-config
  namespace: nexterp
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/nexterp"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  LOG_LEVEL: "INFO"
